### ISSUE TITLE
`mouse_up` event doesn't fire

### ISSUE THREAD

**Issue by Jummit** [Merith-TK/cc-restitched#11]
MC Version: 1.16
CC Version: v1.19.2

The mouse_up event is not emitted, which breaks nearly all GUI applications.

Steps to reproduce:
```
lua
while true do print(os.pullEvent()) end
```
Click, and notice no mouse_up events.

Seems like https://github.com/Merith-TK/cc-restitched/blob/a80302c513c08229998fbeff9842e93df9a7da64/src/main/java/dan200/computercraft/client/gui/widgets/WidgetTerminal.java#L234 is never called.

**Comment by Merith-TK** [comment]
Please update to the latest CC:R release and try again? Your CC version you have listed is out of date

**Comment by Jummit** [comment]
I tested it on 1.194.1, but as the code was not modified, nothing changed: https://github.com/Merith-TK/cc-restitched/commits/173ea720011ea265726d434441f10708a7d798f5/src/main/java/dan200/computercraft/client/gui/widgets/WidgetTerminal.java
