### ISSUE TITLE
turtle.getItemDetail with advanced flag does not return extra data

### ISSUE THREAD

**Issue by fatboychummy** [Merith-TK/cc-restitched#41]
# User Information
Minecraft version: 1.16.5
CC:R version: 1.95.3

# Bug Information

In CC:T, running `turtle.getItemDetail(anySlot, true)` should give more advanced data about an item, including some nbt data for some things. However, this does not happen, and it returns the exact same result to `turtle.getItemDetail(anySlot)`.

# Images

![unknown-61](https://user-images.githubusercontent.com/39929480/119908001-d3469e00-bf0e-11eb-83b6-5f5f14f610f8.png)
![unknown-63](https://user-images.githubusercontent.com/39929480/119908056-f1ac9980-bf0e-11eb-8f48-4683f6b56c10.png)

The above images should have a lot more data, including a `displayName` field.

# Links
[The beginning of the short discussion on discord.](https://discord.com/channels/477910221872824320/477911902152949771/847608698699513856)

**Comment by hugeblank** [comment]
Seems like the functionality is entirely missing within the turtle API. Working on adding it, but kinda confused at what point it vanished.
