### ISSUE TITLE
[Bug][Unreproducable] crash when moved further than menu can remain open

### ISSUE THREAD

**Issue by Merith-TK** [Merith-TK/cc-restitched#44]
## Useful information to include:
 - Minecraft version: 1.16.5
 - CC: Tweaked version: 1.95.3
 - Detailed reproduction steps: Leaving access range while inside computer causes crash
 
 You know how when you are moved far enough away from something like a chest or crafting table, how you are pulled out of the menu?

yeah that dont happen. Buddy teleported me across dimensions while doing admin stuff, without warning (like he usually does, and yes it annoys me, but ive learned to deal with it), and I just crashed

https://mclo.gs/gELQgtU
[crash-2021-06-02_14.09.56-client.txt](https://github.com/Merith-TK/cc-restitched/files/6587450/crash-2021-06-02_14.09.56-client.txt)

**Comment by hugeblank** [comment]
On this! I already see the fix.

**Comment by hugeblank** [comment]
I can't seem to reproduce this, I tried running with just a client, and then using a client and a server. Neither crashed, I got kicked out of the screen, and teleporting worked as intended.

**Comment by Merith-TK** [comment]
try on connected to a server, and then teleport across dimensions

**Comment by hugeblank** [comment]
I did, and still couldn't reproduce :(

**Comment by Merith-TK** [comment]
Odd

**Comment by hugeblank** [comment]
In fairness there's a large amount of other mods in there, at a glance. Could be an interop issue with one of them.

**Comment by Merith-TK** [comment]
Could be ye
