### ISSUE TITLE
Add the compatibility with dpaste

### ISSUE THREAD

**Issue by Maelep** [Merith-TK/cc-restitched#5]
Add the possibility to use dpaste instead of pastebin.com
Like
https://dpaste.com/api/v2/
https://paste.mozilla.org/

**Comment by Merith-TK** [comment]
This is currently a feature pairity fork with bugfixes for fabric, 
You could try making a modified pastebin program and add it to your world/server with a datapack as described here
https://github.com/SquidDev-CC/datapack-example

Please send feature requests here https://github.com/SquidDev-CC/CC-Tweaked, then when I get to the commit where it is added, It will get added to this version. 

If you really want it in CC:R, i reccomend the datapack route for now,

**Comment by 3prm3** [comment]
> Add the possibility to use dpaste instead of pastebin.com
> Like
> https://dpaste.com/api/v2/
> https://paste.mozilla.org/

If you want it in my fork then if you make it then I will implement it in a pull request or I'll try learning more about lua to make a dpaste command based on the pastebin command.
~~3prm3~~

**Comment by Merith-TK** [comment]
> > Add the possibility to use dpaste instead of pastebin.com
> > Like
> > https://dpaste.com/api/v2/
> > https://paste.mozilla.org/
> 
> If you want it in my fork then if you make it then I will implement it in a pull request or I'll try learning more about lua to make a dpaste command based on the pastebin command.
> ~~ 3prm3 ~~

I have taken a look at your fork. You have straight up stolen code and not given credit to those who originally made it.

**Comment by 3prm3** [comment]
> > > Add the possibility to use dpaste instead of pastebin.com
> > > Like
> > > https://dpaste.com/api/v2/
> > > https://paste.mozilla.org/
> > 
> > 
> > If you want it in my fork then if you make it then I will implement it in a pull request or I'll try learning more about lua to make a dpaste command based on the pastebin command.
> > ~~ 3prm3 ~~
> 
> I have taken a look at your fork. You have straight up stolen code and not given credit to those who originally made it.

i removed the copied code

**Comment by 3prm3** [comment]
https://github.com/3prm3/cc-retweaked/commit/d890bfef0c11cc3581d4bea351f4f95a811956d6

**Comment by 3prm3** [comment]
https://github.com/3prm3/cc-retweaked/commit/d5228bde2ff9dbbd9f0e4b8fb2fa72be7070a5ab

**Comment by 3prm3** [comment]
> > > Add the possibility to use dpaste instead of pastebin.com
> > > Like
> > > https://dpaste.com/api/v2/
> > > https://paste.mozilla.org/
> > 
> > 
> > If you want it in my fork then if you make it then I will implement it in a pull request or I'll try learning more about lua to make a dpaste command based on the pastebin command.
> > ~~ 3prm3 ~~
> 
> I have taken a look at your fork. You have straight up stolen code and not given credit to those who originally made it.

sorry for the copyin

> > > Add the possibility to use dpaste instead of pastebin.com
> > > Like
> > > https://dpaste.com/api/v2/
> > > https://paste.mozilla.org/
> > 
> > 
> > If you want it in my fork then if you make it then I will implement it in a pull request or I'll try learning more about lua to make a dpaste command based on the pastebin command.
> > ~~ 3prm3 ~~
> 
> I have taken a look at your fork. You have straight up stolen code and not given credit to those who originally made it.

sorry for copying

**Comment by 3prm3** [comment]
> > > Add the possibility to use dpaste instead of pastebin.com
> > > Like
> > > https://dpaste.com/api/v2/
> > > https://paste.mozilla.org/
> > 
> > 
> > If you want it in my fork then if you make it then I will implement it in a pull request or I'll try learning more about lua to make a dpaste command based on the pastebin command.
> > ~~ 3prm3 ~~
> 
> I have taken a look at your fork. You have straight up stolen code and not given credit to those who originally made it.

the copied code was cause of the pull request not working
