### ISSUE TITLE
[Bug] Turtles do not return `mouse_up` event

### ISSUE THREAD

**Issue by Merith-TK** [Merith-TK/cc-restitched#51]
## Useful information to include:
 - Minecraft version: 1.16.5
 - CC: Restitched version: 1.96.0 hotfix 1 
 - Detailed reproduction steps: sometimes I can spot a bug pretty easily, but often it's much more obscure. The more information I have to help reproduce it, the quicker it'll get fixed.

turtles do not return mouse up event

**Comment by Toad-Dev** [comment]
I poked around in the debugger and found that the mouse event packet (don't remember the class name I'm on mobile) isn't being sent to the server for turtle mouse_up's. I didn't have time to trace it further back but it's a bit of a head scratcher as turtles and computers share most of their code along that path and computers are working.

**Comment by hugeblank** [comment]
It's definitely a client side thing. having a program that just listens for mouse_up events shows that they fire when opening up the turtle GUI, but otherwise don't.

**Comment by hugeblank** [comment]
found the issue, will be committing fix soon :D

**Comment by hugeblank** [comment]
Actually I lie. I'm going to do a refactor, a lot of the code between computer and turtle is shared, and to prevent future issues like this from cropping up I'll have both GUIs extend from one abstract class.

**Comment by SquidDev** [comment]
@hugeblank Can you explain the problem? I couldn't see anything off with the GuiTurtle code in its current state.

**Comment by hugeblank** [comment]
> 
> 
> @hugeblank Can you explain the problem? I couldn't see anything off with the GuiTurtle code in its current state.

The issue was that GuiTurtle was missing the `mouseRelease` method.

**Comment by Toad-Dev** [comment]
I haven't looked at the newest commit, but in `GuiComputer` there is this override handler:

 `@Override public boolean mouseReleased( double mouseX, double mouseY, int button )`

It doesn't exist on forge because the super handler doesn't seem to consume the mouse release event over there. I does on fabric though so not having that same handler in GuiTurtle is what's causing the bug.

**Comment by SquidDev** [comment]
Ahhh, joys of Forge patching things (well and, fixing vanilla bugs).
