### ISSUE TITLE
[BUG] Turtles Do not respect Land claim mods such as GetOffMyLawn and Flan

### ISSUE THREAD

**Issue by i-like-trains72** [Merith-TK/cc-restitched#55]
## Useful information to include:
 - 1.16.5
 - 1.95.3 beta (whatever is currently used in the AOF3 modpack
 - N/A
 - Get the GOML mod, and open to LAN on a world with a friend. Allow the friend to make a claim anchor using GOML and then make yourself a mining turtle. Attempt to use the mining turtle in the claim (make sure you are not trusted in the claim). 
 - Expected Behavior: Nothing should be mined
 - What actually happens: Blocks are mined, thus bypassing the claim

**Comment by Merith-TK** [comment]
also does not respect flan claims as well,

**Comment by hugeblank** [comment]
CC:T had to fix this a while ago. What did we break that removed the checks?

**Comment by Merith-TK** [comment]
> CC:T had to fix this a while ago. What did we break that removed the checks?

Never worked in the first place.

**Comment by JemmaZZ** [comment]
I can confirm that commit ca40c9c fixes this issue.
