### ISSUE TITLE
Crash when activating piston

### ISSUE THREAD

**Issue by joecharamut** [Merith-TK/cc-restitched#79]
Minecraft 1.17.1
CC: R 1.97.1-beta
Fabric API 0.40.8+1.17

Crash Report: [crash-2021-10-14_01.21.48-server.txt](https://github.com/Merith-TK/cc-restitched/files/7343222/crash-2021-10-14_01.21.48-server.txt)
Log: [latest.log](https://github.com/Merith-TK/cc-restitched/files/7343225/latest.log)

Reproduction Steps:
1. Activate a piston (i.e. power it with redstone)
2. Game crashes

**Comment by Merith-TK** [comment]
***nani dafuq???***

Never seen that happen before... like at all,

**Comment by Merith-TK** [comment]
if it happens on linux, server hosts will have an absolute nightmare with it. since the vast majority of them use linux in the first place.

and I was able to reproduce the bug on windows.
