### ISSUE TITLE
Why are github actions failing?

### ISSUE THREAD

**Issue by 3prm3** [Merith-TK/cc-restitched#8]
Why are they failing?

**Comment by Merith-TK** [comment]
Probably because I don't know how to use them and make them work for this.

Please elaborate more than just "Why are they failing"

**Comment by 3prm3** [comment]
> Probably because I don't know how to use them and make them work for this.
> 
> Please elaborate more than just "Why are they failing"

https://github.com/3prm3/cc-retweaked/runs/2336605170?check_suite_focus=true

**Comment by 3prm3** [comment]
> Probably because I don't know how to use them and make them work for this.
> 
> Please elaborate more than just "Why are they failing"

* What went wrong:
Task 'luaJavadoc' not found in root project 'cc-retweaked'. Some candidates are: 'javadoc'.

**Comment by Merith-TK** [comment]
Ah, that is because this fork does not contain the documentation for CC:R/T in it, as it aims to be on par with [CC:T's Documenation](https://tweaked.cc)
