### ISSUE TITLE
Shaders Break Monitors

### ISSUE THREAD

**Issue by Merith-TK** [Merith-TK/cc-restitched#9]
## Useful information to include:
 - MC: 1.16.5
 - CC:R: 1.94.1-beta

Certain Shaders break monitors
- BSL 8.0.01
  * Colors are askewed, most notable with "black", turns grey
- Complimentary Shaders 3.11
  * Same as BSL  
- SEUS Renewed 1.0.1
  * Monitors show background color, thats it.

Please do add onto this list with symptoms from other shaderpacks

**Comment by Merith-TK** [comment]
* Optifine Internal Shaders
  * Not specific to CC:R, but when holding pocket computer, item rendering in hand is scuffed, you can see water/clouds through it, everything else is black

**Comment by 3prm3** [comment]
> ## Useful information to include:
> * MC: 1.16.5
> * CC:R: 1.94.1-beta
> 
> Certain Shaders break monitors
> 
> * BSL 8.0.01
>   
>   * Colors are askewed, most notable with "black", turns grey
> * Complimentary Shaders 3.11
>   
>   * Same as BSL
> * SEUS Renewed 1.0.1
>   
>   * Monitors show background color, thats it.
> 
> Please do add onto this list with symptoms from other shaderpacks

No one uses optiforge

**Comment by Merith-TK** [comment]
Actually, alot of people do, please only post comments here relating to symptoms of certain shaderpacks so that I can keep track of which ones work so i can tell people.

> > ## Useful information to include:
> > 
> > * MC: 1.16.5
> > * CC:R: 1.94.1-beta
> > 
> > Certain Shaders break monitors
> > 
> > * BSL 8.0.01
> >   
> >   * Colors are askewed, most notable with "black", turns grey
> > * Complimentary Shaders 3.11
> >   
> >   * Same as BSL
> > * SEUS Renewed 1.0.1
> >   
> >   * Monitors show background color, thats it.
> > 
> > Please do add onto this list with symptoms from other shaderpacks
> 
> No one uses optifabric

**Comment by hugeblank** [comment]
- Canvas Standard Shaders
  - Monitors don't appear to show anything at all unless looked at at the proper angle and position. Reminiscent of what optifine shaders would do to CC.
![image](https://user-images.githubusercontent.com/16393543/120462452-d0550e80-c34f-11eb-85e2-49f3d8c15060.png)

**Comment by hugeblank** [comment]
Using FREX feels like the move, if at all possible. Most mods that provide rendering solutions aside from vanilla seem to be moving to support it. I also say 'if at all possible' since I have no clue if FREX would be able to handle what CC does.

**Comment by SquidDev** [comment]
@Merith-TK It's possibly worth adding a config option for the monitor rendering backend (Zundrel/cc-tweaked-fabric#). This way people can switch to the VBO backend (which fixes some of the monitor issues).

**Comment by hugeblank** [comment]
This sounds like something within my capabilities. I'll get a PR for this going tomorrow, and then from there see if the VBO option really fixes things.

**Comment by hugeblank** [comment]
Just some preliminary testing using canvas shows that it works, kinda...?
It only seems to properly render the dark part of the terminal when attached to a computer, and even that functional portion has some layering issues (see the water on the far right of the image). 
![image](https://user-images.githubusercontent.com/16393543/120475933-d999a780-c35e-11eb-9d94-ef4e5988ad5f.png)

This might fix things for some of the other shaders though so I'll carry on.

**Comment by Merith-TK** [comment]
> @Merith-TK It's possibly worth adding a config option for the monitor rendering backend (Zundrel/cc-tweaked-fabric#). This way people can switch to the VBO backend (which fixes some of the monitor issues).

Yeah, once we get the config working

Unfortunately it seems the config files in the src, only do the "per world" config that is shown in CC:T, rather than the global config, which is, as you can imagine, problematic, and only leads to MORE WORK being done to rewrite the config system...

**Comment by hugeblank** [comment]
Just wanted to show that yes, the VBO backend @SquidDev suggests does work in all cases aside from canvas:

- Seus Renewed 1.0.1
![image](https://user-images.githubusercontent.com/16393543/120542527-0c17c480-c3a0-11eb-97bf-dfda46b7c559.png)
- BSL 8.0.01
![image](https://user-images.githubusercontent.com/16393543/120542704-441f0780-c3a0-11eb-9738-b57ef20bf975.png)
- Complementary Shaders 3.11
![image](https://user-images.githubusercontent.com/16393543/120542871-76c90000-c3a0-11eb-8a6a-8eee6b505245.png)

>Unfortunately it seems the config files in the src, only do the "per world" config that is shown in CC:T, rather than the global config, which is, as you can imagine, problematic, and only leads to MORE WORK being done to rewrite the config system...

I'm not sure I totally understand the extent of the issue with configs. I've seen mention that if the max monitor widths and heights are not identical between client and server, problems happen. If there are more than these two maybe an issue should be reported? It would be useful to have a full list available of the to-do options needed to maintain parity with CC:T.

**Comment by Merith-TK** [comment]
> I'm not sure I totally understand the extent of the issue with configs.

Simple

`computercraft.java` defines global defaults and then calls a function in `config.java`

`config.java` sets the values to things read from the config file

in `config.java` where it should read the config file, it instead sets those values to the ones defined in `computercraft.java`


it essentially does this logic

`a=b=c=a`

without ever reading the file,

Shit i dont even know where it WRITES the file in the code

**Comment by hugeblank** [comment]
> and even that functional portion has some layering issues (see the water on the far right of the image).

I have found out that this is a vanilla issue with VBO rendering. I'm gonna look into this because I feel like it's a simple fix.
![image](https://user-images.githubusercontent.com/16393543/120579557-94b45600-c3dc-11eb-9acf-5ac36e0dbf3d.png)

**Comment by Merith-TK** [comment]
wait. this is vanillia bug. not shader bug?

**Comment by 3prm3** [comment]
> wait. this is vanillia bug. not shader bug?

i think it is a sodium bug

**Comment by Merith-TK** [comment]
> > wait. this is vanillia bug. not shader bug?
> 
> i think it is a sodium bug

Welp, we need to see if its vanillia or nah

**Comment by 3prm3** [comment]
ok

**Comment by 3prm3** [comment]
ill be a tester

**Comment by Merith-TK** [comment]
please refrain from posting twice,

**Comment by 3prm3** [comment]
> please refrain from posting twice,

that is why i deleted a post

**Comment by hugeblank** [comment]
> 
> 
> wait. this is vanillia bug. not shader bug?

The water rendering ahead of the monitor, yes. that's a vanilla issue. I could report it as an issue, but since it's indev using a rendering option that's not configurable to outside users I'll mark it in the project boards

**Comment by 3prm3** [comment]
> wait. this is vanillia bug. not shader bug?
kinda

**Comment by Merith-TK** [comment]
> > wait. this is vanillia bug. not shader bug?
> 
> kinda, there is this weird puzzle repeating pattern
> ![image](https://user-images.githubusercontent.com/70713233/120580453-148ef000-c3de-11eb-8147-85832d66b7a3.png)

That is called aliasing, it is a normal thing in computers in general (mc mod, or nah)

Will be deleting these posts

**Comment by 3prm3** [comment]
> > > wait. this is vanillia bug. not shader bug?
> > 
> > 
> > kinda, there is this weird puzzle repeating pattern
> > ![image](https://user-images.githubusercontent.com/70713233/120580453-148ef000-c3de-11eb-8147-85832d66b7a3.png)
> 
> That is called aliasing, it is a normal thing in computers in general (mc mod, or nah)
> 
> Will be deleting these posts

Im talking about the gaps

**Comment by Merith-TK** [comment]
> Im talking about the gaps, the areas where the sky is showing
THat is an issue that will be marked as "wontfix" as it does not affect players in the slightest

Please refrain from bringing it up

**Comment by 3prm3** [comment]
> > Im talking about the gaps, the areas where the sky is showing
> 
> THat is an issue that will be marked as "wontfix" as it does not affect players in the slightest
> 
> Please refrain from bringing it up
ok

**Comment by Merith-TK** [comment]
> Just wanted to show that yes, the VBO backend @SquidDev suggests does work in all cases aside from canvas:
Should we set VBO as default for now? until config becomes implemented?

**Comment by hugeblank** [comment]
I think so, yes. My only reservation would be that I can't get them to properly render with canvas. However the issue I'm having with canvas is one that I feel should be taken up with them, since it works fine in all other cases, including with other shaders.

**Comment by Merith-TK** [comment]
> I think so, yes. My only reservation would be that I can't get them to properly render with canvas. However the issue I'm having with canvas is one that I feel should be taken up with them, since it works fine in all other cases, including with other shaders.

Yeah canvas has always been scuffed, maybe we should add a check if canvas is installed at some point and switch rendering engines?


Feel free to just directly commit the VBO swap while leaving a comment stating this is a temporary fix for now until we get config done

**Comment by Merith-TK** [comment]
Question, does VBO break canvas?

**Comment by hugeblank** [comment]
> 
> 
> Just some preliminary testing using canvas shows that it works, kinda...?
> It only seems to properly render the dark part of the terminal when attached to a computer, and even that functional portion has some layering issues (see the water on the far right of the image).
> ![image](https://user-images.githubusercontent.com/16393543/120475933-d999a780-c35e-11eb-9d94-ef4e5988ad5f.png)
> 
> This might fix things for some of the other shaders though so I'll carry on.

@Merith-TK Canvas breaks regardless of rendering method. It even breaks monitors _and_ computers, too. Which is why I don't think the canvas issue is our problem. I recall trying with both TBO and VBO and getting equally bad results.

**Comment by Merith-TK** [comment]
https://github.com/grondag/canvas/issues/273 

posted an issue on the canvas repo about this

**Comment by Merith-TK** [comment]
Hey when you make the fix, can you point it out so I can release a version of either incase the VBO build introduces unpredictable issues?

**Comment by Merith-TK** [comment]
With the 1.96.1-beta, optifine issues are "resolved" please set your `config/computercraft-client.toml` to use `VBO` instead of `BEST`
